INSERT INTO ABONNÉS VALUES(1, 'michel', 'rené', 'reneMichel', '123');
INSERT INTO ABONNÉS VALUES(1, 'sylvie', 'sardine', 'sardineSilvie', '123');
INSERT INTO ABONNÉS VALUES(1, 'popole', 'pupule', 'pupo', '123');
INSERT INTO ABONNÉS VALUES(1, 'lola', 'ericson', 'erciLola', '123');
INSERT INTO ABONNÉS VALUES(1, 'eragon', 'frodon', 'frodEragon', '123');
INSERT INTO ABONNÉS VALUES(1, 'gandalf', 'bond', 'bonDalf', '123');
INSERT INTO ABONNÉS VALUES(1, 'mister', 'v', 'misterV', '123');
INSERT INTO ABONNÉS VALUES(1, 'jul', 'lesang', 'JULO', '123');
INSERT INTO ABONNÉS VALUES(1, 'arbre', 'platane', 'platanArbre', '123');
INSERT INTO ABONNÉS VALUES(1, 'dark', 'vador', 'ouioui', '123');

INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 12, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'sardineSilvie'), 13, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'frodEragon'), 13, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'ouioui'), 13, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'), 13, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'misterV'), 14, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'platanArbre'), 14, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'),55, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'), 30, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'), 80, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'), 70, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'ouioui'), 70, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'bonDalf'), 70, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'JULO'), 432, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'bonDalf'), 80, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'bonDalf'), 432, GETDATE(), GETDATE(), null);








