INSERT INTO ABONNÉS VALUES(1, 'michel', 'rené', 'reneMichel', '123');

INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 1, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 2, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 3, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 4, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 5, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 6, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 7, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 8, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 9, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 10, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 11, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 12, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 13, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 14, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 15, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 16, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 17, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 18, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 19, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 20, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 21, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 22, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 23, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 24, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 25, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 26, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 27, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 28, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 29, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 30, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 40, GETDATE(), GETDATE(), null);
INSERT INTO EMPRUNTER VALUES((SELECT CODE_ABONNÉ FROM ABONNÉS WHERE LOGIN_ABONNÉ = 'reneMichel'), 41, GETDATE(), GETDATE(), null);







